<?xml version="1.0"?>
<robot name="accurate_noah"
	xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find noah_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/wheel.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/camera_sensor.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/accurate_base_link.urdf.xacro" />
	<xacro:include filename="$(find noah_description)/urdf/caster_link.urdf.xacro" />


	<xacro:property name="M_PI" value="3.14159"/>

	<!-- Whole accurate_base_link dimensions -->
	<xacro:property name="base_width" value="0.16426" />
	<xacro:property name="base_depth" value="0.19" />
	<xacro:property name="base_height" value="0.056" />

	<xacro:property name="caster_radius" value="0.022" />

	<xacro:property name="wheel_length" value="0.02" />
	<xacro:property name="wheel_radius" value="0.05" />

	<xacro:property name="camera_size" value="0.02" />


	<!-- Base Link -->
	<xacro:accurate_base_link />

	<!-- Caster -->
	<xacro:caster caster_radius="${caster_radius}" parent_link="caster_holder_link">
		<origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:caster>


	<!-- Wheels -->
	<xacro:noah_wheel wheel_prefix="left" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}" parent_link="left_wheel_adapter_link">
		<origin xyz="0 ${wheel_length/2} 0" rpy="0 0 0" />
	</xacro:noah_wheel>

	<xacro:noah_wheel wheel_prefix="right" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}" parent_link="right_wheel_adapter_link">
		<origin xyz="0 -${wheel_length/2} 0" rpy="0 0 0" />
	</xacro:noah_wheel>

	<!-- Camera -->
	<xacro:noah_camera camera_size="${camera_size}" parent_link="top_generic_link">
		<!-- 0.0015 is half the heigth of top generic link -->
		<origin xyz="${base_depth/3} 0 ${camera_size/2 + 0.0015}" rpy="0 0 0" />
	</xacro:noah_camera>

	<!-- *******Gazebo specific******* -->

	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<legacyMode>false</legacyMode>
			<alwaysOn>true</alwaysOn>
			<updateRate>20</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeparation>0.2</wheelSeparation>
			<wheelDiameter>0.1</wheelDiameter>
			<torque>20</torque>
			<publishWheelTF>False</publishWheelTF>
			<publishWheelJointState>True</publishWheelJointState>
			<commandTopic>cmd_vel</commandTopic>
			<odometryTopic>odom</odometryTopic>
			<odometryFrame>odom</odometryFrame>
			<robotBaseFrame>base_generic_link</robotBaseFrame>
			<publishOdomTF>true</publishOdomTF>
			<wheelAcceleration>0</wheelAcceleration>
			<wheelTorque>5</wheelTorque>
			<odometrySource>world</odometrySource>
			<rosDebugLevel>1</rosDebugLevel>
		</plugin>
	</gazebo>

</robot>
