min_particles: 100
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
update_min_d: 0.05
update_min_a: 0.05
resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
initial_pose_x: 9.89498
initial_pose_y: 6.147881
initial_pose_a: 0.0
gui_publish_rate: 10.0
save_pose_rate: 0.5
use_map_topic: false
first_map_only: false
selective_resampling: false
laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 100
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field
odom_model_type: diff-corrected
odom_alpha1: 0.002
odom_alpha2: 0.002
odom_alpha3: 0.002
odom_alpha4: 0.002
odom_alpha5: 0.002
odom_frame_id: odom
base_frame_id: base_generic_link
global_frame_id: map
tf_broadcast: true
